# example config.yml file with default params

protein: src/EasyMD/tests/data/4zgm.pdb
steps: 2000
step_size: 0.002
friction_coeff: 1
interval: 1000
temperature: 300

solvate: false
GBIS: True
padding: 10
water_model: tip3p
positive_ion: Na+
negative_ion: Cl-
ionic_strength: 0.1
no_neutralize: false

equilibration_steps: 200
protein_force_field: amber14-all.xml
ligand_force_field: openff-2.2.0
water_force_field: amber/tip3p_standard.xml

remove:
  - DMS
  - 32M
ph: 7.0

restart: false

simulated_annealing: false
