name: mdEnv
channels:
  - conda-forge
  - omnia
  - bioconda
  - defaults
dependencies:
  - mdtraj=1.10.0
  - numpy=1.26.4
  - openbabel=3.1.1
  - openff-amber-ff-ports=0.0.4
  - openff-forcefields=2024.04.0
  - openff-interchange=0.3.27
  - openff-interchange-base=0.3.27
  - openff-models=0.1.2
  - openff-toolkit=0.16.1
  - openff-toolkit-base=0.16.1
  - openff-units=0.2.2
  - openff-utilities=0.1.12
  - openmm=8.1.1
  - openmmforcefields=0.13.0
  - pandas=2.2.2
  - pdbfixer=1.9
  - yaml
