import sys, time, argparse
import EasyMD.utils.utils as utils

from EasyMD.utils.simulated_annealing import simulated_annealing
from EasyMD.simRunner import SimRunner
from .sysGenerator.sysGenerator import SysGenerator
#from EasyMD.argManager import ArgManager
from .argManager.manager import ArgManager
from .analysis.analysisManager import AnalysisManager
from .analysis.analysisRunner import AnalysisRunner
from .info.infoManager import InfoManager
from .info.infoRunner import InfoRunner


def run_info():
    """
    Run PDB structure information mode.
    
    This function handles the info subcommand, creating an info parser
    and running structural analysis on PDB files.
    """
    parser = argparse.ArgumentParser(
        prog='EasyMD info',
        description="""EasyMD PDB Structure Information Tool
        
Analyze PDB files to extract detailed structural information including
chain analysis, missing residues, ligands, water molecules, disulfide bonds,
metal ions, and modified residues.""",
        epilog="""Examples:
  # Basic structure analysis
  python -m EasyMD info protein.pdb
  
  # Analyze with custom output file
  python -m EasyMD info protein.pdb --output protein_analysis.info
  
  # Summary format only
  python -m EasyMD info protein.pdb --format summary
  
  # JSON output for programmatic use
  python -m EasyMD info protein.pdb --format json
  
  # Terminal output only (no file)
  python -m EasyMD info protein.pdb --no-file
  
  # Custom disulfide bond detection
  python -m EasyMD info protein.pdb --disulfide-distance 3.0

Output Files:
  - detailed report: <pdb_name>.info (default)
  - custom report: specified with --output
  - terminal display with colored formatting

Analysis Features:
  - Chain composition and sequence analysis
  - Missing residue detection and gap analysis
  - Ligand and small molecule identification
  - Water molecule distribution analysis
  - Disulfide bond prediction
  - Metal ion detection
  - Modified residue identification

For more information, visit: https://github.com/JacobCote/EasyMD""",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    try:
        info_manager = InfoManager(parser)
        config = info_manager.get_args()
        
        # Run the analysis
        runner = InfoRunner(config)
        runner.run()
        
    except KeyboardInterrupt:
        print("\n\n⚠️  Analysis interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Analysis failed: {str(e)}")
        sys.exit(1)


def run_analysis():
    """
    Run trajectory analysis mode.
    
    This function handles the analysis subcommand, creating an analysis parser
    and running the selected analyses on trajectory data.
    """
    parser = argparse.ArgumentParser(
        prog='EasyMD analyze',
        description="""EasyMD Trajectory Analysis Tool
        
Analyze molecular dynamics trajectories generated by EasyMD simulations.
Supports RMSD, RMSF, inter-chain distances, radius of gyration, and 
secondary structure analysis.""",
        epilog="""Examples:
  # Calculate RMSD and RMSF
  python -m EasyMD analyze out_0/ --rmsd --rmsf
  
  # Perform all analyses and save data
  python -m EasyMD analyze out_0/ --all --save-data
  
  # Custom analysis with specific parameters
  python -m EasyMD analyze out_0/ --rmsd --atom-selection backbone \\
                   --reference-frame 10 --skip-frames 5
  
  # Generate high-quality plots
  python -m EasyMD analyze out_0/ --rmsf --output-format pdf --dpi 600
  
  # Analyze specific frame range
  python -m EasyMD analyze out_0/ --rmsd --start-frame 1000 --end-frame 5000

Output Files:
  - analysis plots: rmsd.png, rmsf.png, etc.
  - data files: rmsd_data.csv, rmsf_data.csv (with --save-data)
  - analysis summary in terminal

For more information, visit: https://github.com/JacobCote/EasyMD""",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    try:
        analysis_manager = AnalysisManager(parser)
        config = analysis_manager.get_args()
        
        # Run the analysis
        runner = AnalysisRunner(config)
        runner.run()
        
    except KeyboardInterrupt:
        print("\n\n⚠️  Analysis interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Analysis failed: {str(e)}")
        sys.exit(1)


def main():
    # Check if this is an analysis command
    if len(sys.argv) > 1 and sys.argv[1] == 'analyze':
        # Remove 'analyze' from sys.argv and run analysis
        sys.argv.pop(1)
        run_analysis()
        return
    
    # Check if this is an info command
    if len(sys.argv) > 1 and sys.argv[1] == 'info':
        # Remove 'info' from sys.argv and run info analysis
        sys.argv.pop(1)
        run_info()
        return
    
    # Regular simulation mode
    parser = argparse.ArgumentParser(
        prog='EasyMD',
        description="""EasyMD - Easy Molecular Dynamics Simulation Package
        
A comprehensive toolkit for setting up and running molecular dynamics simulations
with OpenMM. Supports protein-only and protein-ligand systems with both explicit
and implicit solvation.""",
        epilog="""Examples:
  # Basic protein simulation (10 ns, explicit solvent)
  python -m EasyMD --protein protein.pdb --steps 5000000 --solvate
  
  # Protein-ligand complex with custom parameters
  python -m EasyMD --protein complex.pdb --ligand ATP --steps 10000000 \\
                   --solvate --temperature 310 --ionic-strength 0.1
  
  # Fast implicit solvent simulation
  python -m EasyMD --protein protein.pdb --steps 1000000 --GBIS \\
                   --temperature 300 --step-size 0.002
  
  # Simulation with time-based duration
  python -m EasyMD --protein protein.pdb --clock 50ns --solvate
  
  # Keep crystal waters and use custom force fields
  python -m EasyMD --protein protein.pdb --steps 5000000 --solvate \\
                   --keep-water --protein-force-field amber99sb-ildn.xml
  
  # Restart from previous simulation
  python -m EasyMD --restart out_0/
  
  # Using configuration file
  python -m EasyMD --config my_simulation.yml

Analysis:
  # Analyze trajectory from simulation output directory
  python -m EasyMD analyze out_0/ --rmsd --rmsf --save-data
  
  # Perform all analyses with custom output
  python -m EasyMD analyze out_0/ --all --output-dir analysis_results

Structure Information:
  # Get detailed PDB structure information
  python -m EasyMD info protein.pdb
  
  # Generate summary report
  python -m EasyMD info protein.pdb --format summary

Output Files:
  - trajectory files: output_traj_*.dcd
  - log file: log.txt (energies, temperature, etc.)
  - final structure: last_state_*.pdb
  - system topology: topology.pkl
  - restart files: last_state.xml, restart_setup.yml

For more information and tutorials, visit: https://github.com/JacobCote/EasyMD""",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    argManager = ArgManager(parser)
    config = argManager.get_args()
    
    
    config.outdir = utils.get_outdir(config)
    

           



    # get the chosen or fastest platform
    platform = utils.get_platform()

    ## system preparation
    sysGenerator = SysGenerator(config)
    

    ## simulaton prep 
    sim = SimRunner(config,sysGenerator.modeller,sysGenerator.system)

    ## start sim
    sim.run()


if __name__ == "__main__":

    main()

